
/********************************************************************
* NAME:                                                             *
*                                                                   *
* PURPOSE:                                                          *
*                                                                   *
* GLOBAL VARIABLES:                                                 *
*                                                                   *
* Variable:                                                         *
*                                                                   *
* Type:                                                             *
*                                                                   *
* Description:                                                      *
*                                                                   *
*                                                                   *
* DEVELOPMENT HISTORY:                                              *
*                                                                   *
* Date:                                                             *
*                                                                   *
* Author:                                                           *
*                                                                   *
* Change Id:                                                        *
*                                                                   *
* Release:                                                          *
*                                                                   *
* Description of change:                                            *
*                                                                   *
*********************************************************************/

/* for debug prints */
#ifndef LOGMODE
#define DEBUG_PRT
#endif

/* for saving phoneram */
//#define SAVE_PHONERAM

/* for saving MAP blocks in separate files */
//#define SAVE_BINARY_MAP

/* with or without dongle */
//#define USE_DONGLE
