
/********************************************************************
* NAME:                                                             *
*                                                                   *
* PURPOSE:                                                          *
*                                                                   *
* GLOBAL VARIABLES:                                                 *
*                                                                   *
* Variable:                                                         *
*                                                                   *
* Type:                                                             *
*                                                                   *
* Description:                                                      *
*                                                                   *
*                                                                   *
* DEVELOPMENT HISTORY:                                              *
*                                                                   *
* Date:                                                             *
*                                                                   *
* Author:                                                           *
*                                                                   *
* Change Id:                                                        *
*                                                                   *
* Release:                                                          *
*                                                                   *
* Description of change:                                            *
*                                                                   *
*********************************************************************/

#ifndef __map_loc_h
#define __map_loc_h

#define MAP_IMEI_BLOCK_ID_STR "IMEI Block "

#define MAP_C30_IMEI_BLOCK_ID_STR "Resurrect data "

#define MAP_LAST_IMEI_BLOCK 3

#define MAP_LAST_C30_IMEI_BLOCK 0

#define MAP_MODEL_ID "[Model: "

#define MAP_IMEI_ID "[Desired IMEI: "

#define MAP_PHONE_ID "[PhoneID: "

#define MAP_BLOCK_END_CHR ']'

#define MAP_MANUFACTURER_ID "Siemens"

#define MAP_ID_BLOCK_ID_STR "ID: "

#endif
