copy c35.bin loaders\data01un.004
del c35.bin
copy a35.bin loaders\data01un.008
del a35.bin
copy c45.bin loaders\data01un.012
del c45.bin
copy s45.bin loaders\data01un.016
del s45.bin
copy sl42.bin loaders\data01un.020
del sl42.bin
copy c30.bin loaders\data01un.024
del c30.bin
copy s40.bin loaders\data01un.028
del s40.bin
copy a50.bin loaders\data01un.032
del a50.bin
copy c55.bin loaders\data01un.036
del c55.bin
copy s55.bin loaders\data01un.040
del s55.bin
copy mt50.bin loaders\data01un.044
del mt50.bin
del loaders\data01.dat
cd loaders
pack2a.exe
cd ..
